<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

## Загрузка данных

In [514]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [515]:
data = pd.read_csv('/datasets/insurance.csv')
display(data)
data.info()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0       1     41.0   49600.0            1                  0
1       0     46.0   38000.0            1                  1
2       0     29.0   21000.0            0                  0
3       0     21.0   41700.0            2                  0
4       1     28.0   26100.0            0                  0
...   ...      ...       ...          ...                ...
4995    0     28.0   35700.0            2                  0
4996    0     34.0   52400.0            1                  0
4997    0     20.0   33900.0            2                  0
4998    1     22.0   32700.0            3                  0
4999    1     28.0   40600.0            1                  0

[5000 rows x 5 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Пол                5000 non-null   int64  
 1   Возраст            5000 non-null   float64
 2   Зарплата           5000 non-null   float64
 3   Члены семьи        5000 non-null   int64  
 4   Страховые выплаты  5000 non-null   int64  
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


In [516]:
data.isna().sum()

Пол                  0
Возраст              0
Зарплата             0
Члены семьи          0
Страховые выплаты    0
dtype: int64

В данных нет пропусков

In [517]:
data.duplicated().sum()

153

In [518]:
data[data.duplicated()].head(10)

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
281     1     39.0   48100.0            1                  0
488     1     24.0   32900.0            1                  0
513     0     31.0   37400.0            2                  0
718     1     22.0   32600.0            1                  0
785     0     20.0   35800.0            0                  0
869     1     24.0   33100.0            1                  0
887     1     19.0   35500.0            0                  0
1004    1     29.0   42400.0            0                  0
1089    0     27.0   46800.0            2                  0
1091    1     41.0   34000.0            1                  0

И нет дубликатов

## Умножение матриц

Выделим признаки и ключевой признак. Разделим наш датафрэйм на обучающую и валдивационную выборки

In [519]:
features = data.drop(['Страховые выплаты'], axis=1)
target = data['Страховые выплаты']
features_train, features_valid, target_train, target_valid = train_test_split(features, target, 
                                                                              test_size=0.25, random_state=123)

In [520]:
model = LinearRegression()
model.fit(features_train, target_train)
predicted_valid = model.predict(features_valid)
score_1 = r2_score(target_valid, predicted_valid)
score_1

0.43018469990933306

Создадим случайную квадратную матрицу, размеры который равны количеству признаков

In [521]:
matrix = np.random.random((4, 4))
matrix

array([[0.44452536, 0.10787037, 0.74189122, 0.32883339],
       [0.83044996, 0.41112999, 0.99970197, 0.21707797],
       [0.54189067, 0.49023941, 0.5755197 , 0.36539704],
       [0.69668663, 0.52287202, 0.89327045, 0.0708507 ]])

In [522]:
matrix_inv = np.linalg.inv(matrix)
matrix_inv

array([[-4.29371053,  8.15171257,  0.11280289, -5.62957982],
       [-0.19074578, -3.80232019,  1.7995489 ,  3.25436018],
       [ 3.35409937, -4.08861792, -1.31833137,  3.75893797],
       [ 1.3406855 , -0.54792349,  2.23151519, -1.93800606]])

In [523]:
matrix @ matrix_inv

array([[ 1.00000000e+00,  6.70525839e-16,  6.66741128e-17,
         9.38691021e-17],
       [-5.87086319e-16,  1.00000000e+00, -7.04608872e-17,
        -6.66260942e-16],
       [-1.84485089e-16,  1.13655830e-15,  1.00000000e+00,
        -4.39953416e-16],
       [-8.40064157e-16,  6.05913929e-16, -3.32032605e-16,
         1.00000000e+00]])

Наша матрица matrix обратима, потому что для нее можно найти обратную матрицу. Умножим признаки на обратимую матрицу

In [524]:
features = data.drop(['Страховые выплаты'], axis=1)
target = data['Страховые выплаты']
features = features @ matrix
features_train, features_valid, target_train, target_valid = train_test_split(features, target, 
                                                                              test_size=0.25, random_state=123)

In [525]:
model = LinearRegression()
model.fit(features_train, target_train)
predicted_valid = model.predict(features_valid)
score_2 = r2_score(target_valid, predicted_valid)
score_2

0.43018469990879227

In [526]:
score_1-score_2

5.407896352949138e-13

Умножение признаков на обратимую матрицу не повлияло на результат предсказания линейной регресии

## Алгоритм преобразования

**Алгоритм**

In [527]:
def algorithm(features):
    import random
    m = []
    for i in range(4):
        matrix = np.random.random((4, 4))
        m.append(matrix)
    for i in range(len(m)):
        features = features @ m[i]
    return features

**Обоснование**

Создаем 4 случайные обратимые матрицы и умнажаем признаки (данные, которые нужно зашифровать) на каждую из этих матриц. Алгоритм хорош тем, что матрицы генирируются случайно, следовательно, нет определенного закона составления матриц

## Проверка алгоритма

In [528]:
features = data.drop(['Страховые выплаты'], axis=1)
features = algorithm(features)
target = data['Страховые выплаты']
features_train, features_valid, target_train, target_valid = train_test_split(features, target, 
                                                                              test_size=0.25, random_state=123)

In [529]:
model = LinearRegression()
model.fit(features_train, target_train)
predicted_valid = model.predict(features_valid)
score_3 = r2_score(target_valid, predicted_valid)
score_3

0.43018470094162053

In [530]:
score_3 - score_1

1.0322874777202173e-09

Преобразование признаков по нашему алгоритму не изменило точность предсказания модели.